Commit with main.

diff --git a/MoinMoin/i18n/Makefile b/MoinMoin/i18n/Makefile
--- a/MoinMoin/i18n/Makefile
+++ b/MoinMoin/i18n/Makefile
@@ -1,6 +1,6 @@
 POFILES = $(wildcard *.po)
 UPDATEPOFILES = $(POFILES:.po=.po-update)
-CATALOGS = $(POFILES:.po=.mo)
+# CATALOGS = $(POFILES:.po=.mo)
 NOPFILES = $(POFILES:.po=.nop)
 DOMAIN = MoinMoin
 
@@ -8,29 +8,33 @@ DOMAIN = MoinMoin
 
 -include POTFILES
 
-POTFILES: POTFILES.in
-	@echo "POTFILES = \\" > POTFILES
-	@sed -e '/^#/d' -e "/^[ ]*\$$/d" -e 's,.*,	../& \\,' -e '$$s/\(.*\) \\/\1/' < POTFILES.in >> POTFILES
+# both POTFILES.in and POTFILES are now generated by the same tool
+#POTFILES: POTFILES.in
+#	@echo "POTFILES = \\" > POTFILES
+#	@sed -e '/^#/d' -e "/^[ ]*\$$/d" -e 's,.*,	../& \\,' -e '$$s/\(.*\) \\/\1/' < POTFILES.in >> POTFILES
 
-.po.mo:
-	@lang=`echo $@ | sed -e 's/\.mo$$//'`; \
-	msgfmt $$lang.po -o mo/$$lang.$(DOMAIN).mo
+POTFILES.in POTFILES:
+	tools/mk_POTFILES.py
+
+#.po.mo:
+#	@lang=`echo $@ | sed -e 's/\.mo$$//'`; \
+#	msgfmt $$lang.po -o mo/$$lang.$(DOMAIN).mo
 
 .nop.po-update:
-	@lang=`echo $@ | sed -e 's/\.po-update$$//'`; \
+	@lang=`echo $@ | sed -e 's/\.MoinMoin\.po-update$$//'`; \
 	echo "$$lang:"; \
 	tools/wiki2po.py $${lang}; \
-	echo "msgmerge $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
-	if msgmerge $$lang.po $(DOMAIN).pot -o $$lang.new.po; then \
-	  if cmp $$lang.po $$lang.new.po >/dev/null 2>&1; then \
-	    rm -f $$lang.new.po; \
+	echo "msgmerge $$lang.$(DOMAIN).po $(DOMAIN).pot -o $$lang.$(DOMAIN).new.po"; \
+	if msgmerge $$lang.$(DOMAIN).po $(DOMAIN).pot -o $$lang.$(DOMAIN).new.po; then \
+	  if cmp $$lang.$(DOMAIN).po $$lang.$(DOMAIN).new.po >/dev/null 2>&1; then \
+	    rm -f $$lang.$(DOMAIN).new.po; \
 	  else \
-	    echo XXX tools/po2wiki.py $$lang <$$lang.new.po; \
-	    rm -f $$lang.new.po; \
+	    tools/po2wiki.py $$lang <$$lang.$(DOMAIN).new.po; \
+	    rm -f $$lang.$(DOMAIN).new.po; \
 	  fi; \
 	else \
-	  echo "msgmerge for $$lang.po failed!" 1>&2; \
-	  rm -f $$lang.new.po; \
+	  echo "msgmerge for $$lang.$(DOMAIN).po failed!" 1>&2; \
+	  rm -f $$lang.$(DOMAIN).new.po; \
 	fi
 
 # remove "--no-location" if you want to have file names and line numbers
@@ -59,27 +63,24 @@ $(DOMAIN).pot:
 	$(MAKE) $(DOMAIN).pot-update
 
 $(POFILES):
-	@lang=`echo $@ | sed -e 's,.*/,,' -e 's/\.po$$//'`; \
+	@lang=`echo $@ | sed -e 's,.*/,,' -e 's/\.MoinMoin\.po$$//'`; \
 	tools/wiki2po.py $${lang}; \
-	echo msgmerge $${lang}.po $(DOMAIN).pot -o $${lang}.new.po; \
-	msgmerge $${lang}.po $(DOMAIN).pot -o $${lang}.new.po; \
-	echo XXX tools/po2wiki.py $${lang} <$$lang.new.po; \
-	rm -f $$lang.new.po
-	
+	echo msgmerge $${lang}.$(DOMAIN).po $(DOMAIN).pot -o $${lang}.$(DOMAIN).new.po; \
+	msgmerge $${lang}.$(DOMAIN).po $(DOMAIN).pot -o $${lang}.$(DOMAIN).new.po; \
+	tools/po2wiki.py $${lang} <$$lang.$(DOMAIN).new.po; \
+	rm -f $$lang.$(DOMAIN).new.po
 
 $(NOPFILES):
 
 update-po:
-	@echo "Edit Makefile and remove some XXX after finally closing 1.5.x branch,"
-	@echo "no 1.5.x i18n updates will be possible once this is run in 1.6."
 	$(MAKE) $(DOMAIN).pot-update
 	$(MAKE) $(UPDATEPOFILES)
-	$(MAKE) $(CATALOGS)
+#	$(MAKE) $(CATALOGS)
 
 stats:
 	@files="$(POFILES)"; \
 	for i in $$files; do \
-	  lang=`echo $$i | sed -e 's,.*/,,' -e 's/\.po$$//'`; \
+	  lang=`echo $$i | sed -e 's,.*/,,' -e 's/\.MoinMoin\.po$$//'`; \
 	  echo -n "$$lang: "; \
 	  msgfmt -o /dev/null --statistics $$i; \
 	done
